import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SettingsProvider } from "@/context/SettingsContext";
import { Toaster } from "@/components/ui/sonner";
import { PomodoroProvider } from "@/context/PomodoroContext";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The Dev Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <PomodoroProvider>
          <SettingsProvider>{children}</SettingsProvider>
        </PomodoroProvider>
        <Toaster
          toastOptions={{
            unstyled: true,
            classNames: {
              toast:
                "group flex items-center gap-2 rounded-lg border p-4 shadow-md transition-all bg-white",
              error:
                "border-red-400 shadow-red-400/50 text-red-600 [&>svg]:text-red-400 bg-white",
              success:
                "border-green-400 shadow-green-400/50 text-green-600 [&>svg]:text-green-400 bg-white",
              warning:
                "border-yellow-400 shadow-yellow-400/50 text-yellow-600 [&>svg]:text-yellow-400 bg-white",
              info: "border-blue-400 shadow-blue-400/50 text-blue-600 [&>svg]:text-blue-400 bg-white",
            },
          }}
        />
        <Footer />
      </body>
    </html>
  );
}
